$(function(){
	//导航切换
	$(".menuItem").click(function(){
		var _s = $(this);
		_s.addClass("active").siblings().removeClass("active");
	});
	//线上、线下课程
	$("#rMenu>div").hover(function(){
		$(this).addClass("rmcActive").siblings().removeClass("rmcActive");
	});
	//加载更多
	$("#loadMore").click(function(){
		$(this).hide();
		$("#loaded").show();
	});
	$("#loadMore1").click(function(){
		$(this).hide();
		$("#loaded1").show();
	});
});
